services:
  nginx:
    build:
      context: "requirements/nginx"
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - api-anima-terra-static-volume:/var/www/static:ro
      - ./requirements/api/django/medias:/var/www/medias:ro
    networks:
      - frontend_network
    depends_on:
      - frontend
      - api

  frontend:
    build:
      context: "requirements/frontend"
      target: production
      args:
        SITE_URL: ${SITE_URL}
    restart: unless-stopped
    environment:
      SITE_URL: ${SITE_URL}
    networks:
      - frontend_network
    depends_on:
      - api

  api:
    build:
      context: "requirements/api"
      target: production
    depends_on:
      api-db:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - api-anima-terra-static-volume:/code/staticfiles
      - ./requirements/api/django/medias:/code/medias
    environment:
      TZ: Europe/Paris
      DEBUG: "False" # True or False
      MIGRATION: "true" # true or false
      COLLECT_STATIC: "true" # true or false
      SITE_URL: ${SITE_URL}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      SECRET_KEY: ${DJANGO_SECRET_KEY}
    networks:
      - backend_network
      - frontend_network

  api-db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      TZ: Europe/Paris
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - api-anima-terra-db-volume:/var/lib/postgresql/data
    networks:
      - backend_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname=$$POSTGRES_DB --username=$$POSTGRES_USER"]
      interval: 3s
      timeout: 3s
      retries: 10

networks:
  backend_network:
  frontend_network:

volumes:
  api-anima-terra-db-volume:
    name: api-anima-terra-db-volume
  api-anima-terra-static-volume:
    name: api-anima-terra-static-volume
